apiVersion: skaffold/v4beta3
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: colema18/auth
      context: auth
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: colema18/client
      context: client
      sync:
        manual:
          - src: '**/*.js'
            dest: .
      docker:
        dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
      rawYaml:
        - ./infra/k8s/*